version: '3.8'

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    network_mode: host
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    network_mode: host
    ports:
      - "${SERVER_PORT:-10100}:${SERVER_PORT:-10100}"
    environment:
      - SERVER_HOST=${SERVER_HOST:-0.0.0.0}
      - SERVER_PORT=${SERVER_PORT:-10100}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - VERIFY_DOMAIN=${VERIFY_DOMAIN}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MONGODB_DSN=${MONGODB_DSN:-mongodb://mongodb:27017/kitan}
      - REDIS_DSN=${REDIS_DSN:-redis://redis:6379}
      - DEBUG=${DEBUG:-false}
      - CLOUDFLARE_SECRET_KEY=${CLOUDFLARE_SECRET_KEY}
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: