# Dockerfile
FROM python:3.9-slim

# 设置工作目录
WORKDIR /app

# 安装 PDM
RUN pip install -U pip setuptools wheel && \
    pip install pdm

# 复制项目文件
COPY . .

# 复制 .env 文件
COPY .env.example .env

# 安装依赖
RUN pdm install

EXPOSE 22111

# 启动命令
CMD ["pdm", "run", "python", "main.py"]


# 构建
# docker build -t kitan-backend .

# Run
# docker run -d -p 8000:8000 --name kitan-backend-container kitan-backend